name: Playwright Tests for Swag Labs

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows us to manually trigger the workflow from the GitHub Actions UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - suite: login
            command: test:login
          - suite: inventory
            command: test:inventory
          - suite: cart
            command: test:cart
          - suite: checkout
            command: test:checkout
          - suite: inventory-details
            command: test:inventory-details
          - suite: smoke
            command: test:smoke

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn exec playwright install --with-deps

      - name: Run ${{ matrix.suite }} tests
        run: yarn ${{ matrix.command }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-${{ matrix.suite }}
          path: playwright-report
          retention-days: 3
